---
- name: Create TestCR resource
  k8s:
    definition:
      apiVersion: apps.example.com/v1alpha1
      kind: TestCR
      metadata:
        namespace: '{{ namespace }}'
        name: my-test
      spec:
        size: 2

- block:
    - name: Set custom status fields on a CR that does not exist
      k8s_status:
        api_version: apps.example.com/v1alpha1
        kind: TestCR
        name: dne
        namespace: '{{ namespace }}'
        status:
          hello: world
      register: test_cr_failed_1
  rescue:
    - assert:
        that:
          - test_cr_failed_1 is failed
          - test_cr_failed_1.msg == 'Failed to retrieve requested object'
          - test_cr_failed_1.error.status == 404
          - test_cr_failed_1.error.reason == 'Not Found'

- block:
    - name: Set custom status fields on a CR that is not defined
      k8s_status:
        api_version: apps.example.com/v1alpha1
        kind: DNECR
        name: dne
        namespace: '{{ namespace }}'
        status:
          hello: world
      register: test_cr_failed_2
  rescue:
    - assert:
        that:
          - test_cr_failed_2 is failed
          - test_cr_failed_2.msg.startswith('Failed to find exact match for')

- name: Set custom status fields on TestCR
  k8s_status:
    api_version: apps.example.com/v1alpha1
    kind: TestCR
    name: my-test
    namespace: '{{ namespace }}'
    status:
      hello: world
      custom: entries

- name: Get the custom resource
  k8s_info:
    api_version: apps.example.com/v1alpha1
    kind: TestCR
    name: my-test
    namespace: '{{ namespace }}'
  register: test_cr
