---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.kubernetes
    - operator_sdk.util

  tasks:
    - name: Verify cluster is working.
      k8s_info:
        namespace: kube-system
        kind: Pod
      register: pod_list

    - name: Verify cluster has more than 5 pods running.
      assert:
        that: (pod_list.resources | count) > 5

    - name: Create CRD
      k8s:
        src: files/crd.yaml

    - block:
        - name: Create namespace
          k8s:
            kind: Namespace
            name: osdkau-test-doc-examples

        - import_tasks: tasks/doc_examples.yml
          vars:
            namespace: osdkau-test-doc-examples
      always:
        - name: Clean up namespace
          k8s:
            kind: Namespace
            name: osdkau-test-doc-examples
            state: absent
            wait: yes

    - block:
        - name: Create namespace
          k8s:
            kind: Namespace
            name: osdkau-test-advanced-usage

        - import_tasks: tasks/advanced_usage.yml
          vars:
            namespace: osdkau-test-advanced-usage
      always:
        - name: Clean up namespace
          k8s:
            kind: Namespace
            name: osdkau-test-advanced-usage
            state: absent
            wait: yes

    - block:
        - name: Create namespace
          k8s:
            kind: Namespace
            name: osdkau-test-failure-modes

        - import_tasks: tasks/failure_modes.yml
          vars:
            namespace: osdkau-test-failure-modes
      always:
        - name: Clean up namespace
          k8s:
            kind: Namespace
            name: osdkau-test-failure-modes
            state: absent
            wait: yes

    - block:
        - name: Create namespace
          k8s:
            kind: Namespace
            name: osdkau-test-k8s-events

        - import_tasks: tasks/k8s_events.yml
          vars:
            namespace: osdkau-test-k8s-events
      always:
        - name: Clean up namespace
          k8s:
            kind: Namespace
            name: osdkau-test-k8s-events
            state: absent
            wait: yes
