name: ci

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['2.7']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: operator-framework/operator-sdk-ansilbe-util
      
      - name: Set up KinD cluster
        uses: engineerd/setup-kind@v0.5.0

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      
      - name: Install molecule and openshift dependencies
        run: pip install ansible molecule yamllint openshift flake8
      
      - name: Run molecule default test scenario
        run: molecule test
        working-directory: ./operator-framework/operator-sdk-ansilbe-util
