name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.9']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/operator_sdk/util

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible and kubernetes dependencies
        run: pip install ansible-core~=2.15.0 yamllint kubernetes flake8 pycodestyle pylint ansible-lint

      - name: Ensure collection dependency exists
        run: ansible-galaxy collection install kubernetes.core

      - name: Run sanity tests on Python ${{ matrix.python_version }}
        run: TEST_ARGS="--docker --color --python ${{ matrix.python_version }}" make test-sanity
        working-directory: ./ansible_collections/operator_sdk/util
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.9']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/operator_sdk/util

      - name: Set up KinD cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install molecule and kubernetes dependencies
        run: pip install ansible-core~=2.15.0 molecule yamllint kubernetes flake8

      - name: Ensure collection dependency exists
        run: ansible-galaxy collection install kubernetes.core

      - name: Run molecule default test scenario
        run: make test-molecule
        working-directory: ./ansible_collections/operator_sdk/util
