name: ci

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['2.7']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/kubernetes

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible base (devel branch)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check
